### ISSUE TITLE
Missing images of cats

### ISSUE THREAD

**Issue by loom4k** [cats/cat#14]
I think we should add more images of cats or creating a folder with all of them.

**Comment by Phineas** [comment]
this is a great idea, perhaps we should separate the directories by different types & breeds of cats

**Comment by remynln** [comment]
@Phineas maybe this issue can be closed ?

**Comment by cnrad** [comment]
@Waz0x no

**Comment by cnrad** [comment]
do you mind @loom4k we're still working on it

**Comment by loom4k** [comment]
oh yeah sorry i was cleaning up my open pr and issues box. didn't think this was still a thing ;)

**Comment by loom4k** [comment]
Closing this as it's taking up real estate in everyone's issue backlog and probably won't be worked on. If you wanna work on it: open another issue without me linked in it ;)
