### ISSUE TITLE
Use README.md 

### ISSUE THREAD

**Issue by maxichrome** [cats/cat#26]
Hello.

This Formal Business Inquiry regards the use of "DESCRIPTION.md" filenames.

I would like to suggest that all "DESCRIPTION.md" filenames get renamed to "README.md" so that **GitHub will show a preview of the information** inside the directory root.

Please respond to my Formal Business Inquiry at your earliest convenience. Thank you.

~hadenpf

**Comment by maxichrome** [comment]
Addendum to Formal Business Inquiry:

Hello.

I would like to amend my Formal Business Inquiry with the following statement:

To clarify, by "a preview of the information" I meant "the contents of the markdown document."

Thank you for your prompt attention to my Formal Business Inquiry and considering this addendum along with it.

~hadenpf

**Comment by Phineas** [comment]
TRUEEEE

**Comment by Phineas** [comment]
any truers?

**Comment by looskie** [comment]
THATS IN FACT TRUEEEEE (proud truer btw)

**Comment by robertt** [comment]
TRUEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE

(ALSO A TRUER)

**Comment by maxichrome** [comment]
I am also of the belief that this GitHub Issues entry is Truthy.

**Comment by remynln** [comment]
gonna do a pr with files modified

**Comment by ghost** [comment]
![attachment](https://user-images.githubusercontent.com/68010477/127493052-a0515f03-cecc-4a69-9df7-6d40b99d5a42.gif)

**Comment by looskie** [comment]
![image](https://user-images.githubusercontent.com/50378828/127494954-2a173a6f-4cd5-478a-a676-8e7b7c48960a.png)
