### ISSUE TITLE
Feature Request: Add French Translation 

### ISSUE THREAD

**Issue by heybereket** [cats/cat#6]
Hey developers,
It would be nice if you could add french as a translation, alongside every language in the world.

Thanks.

**Comment by Looskie** [comment]
![image](https://user-images.githubusercontent.com/50378828/127038827-ade569e2-a143-49f1-8a65-53718ba8b078.png)

**Comment by Phineas** [comment]
Thank you @Looskie for your hard work and dedication to this issue. I'll be closing it now that it's implemented.

**Comment by heybereket** [comment]
cheers! 👍
